### PR TITLE
rebar3 and hex 

### PR DESCRIPTION
**Pull request by Licenser**
I've made a branch with all the data / changes needed for providing a hex package (as mentioned #13). Please note the following ti things before merging:

1) Merge in a own branch, this changes are **not** compatible with rebar2 since it depends on packages.
2) the `erlang_localtime` package does not exist yet and is needed for this to work. I've a PR prepared for that too but I'm not sure how to handle this best your fork seems to have diverged from the upstream repo quite a bit (judging on your PR for it) I'll send a PR for that to non the less: choptastic/erlang_localtime#3

### CODE REVIEW

**Comment by choptastic** [comment]
Thanks Heinz. I'll merge these into a separate branch for rebar3/hex compatibility for now (don't like breaking things for folks already using rebar2), and I'll eventually tag the rebar3 version as master, and move the rebar2 version to its own branch.

Sound fair?

**Comment by Licenser** [comment]
So I've talked with the rebar3 folks and we found a solution to make ti both rebar3 and rebar2 compatible, I updated the PR. Once we'll have a `erlang_localtime` package `make publish` should do the trick :) and work with both rebar2 and rebar3 (still better to keep it separate for now I think.)

**Comment by Licenser** [comment]
seems rebar3 script is not R14 compatible.

**Comment by choptastic** [comment]
That's fine. I can update the makefile to use the rebar2 scriptcwith r14. I
doubt too many folks still running r14 are using rebar3 :)

**Comment by Licenser** [comment]
very true, I hope not many people are still using R14 ;)

**Comment by choptastic** [comment]
I know a guy (the only other erlang guy in town) who works at a company
that still runs R11. Which is hilarious.

**Comment by choptastic** [comment]
Thanks again. It's merged into master. I tagged the previous version before this as 0.4.1, and this will be the working branch for 0.5.0. I appreciate you lighting a fire under me to hasten my adoption of rebar3. I'd been putting it off because lazy.

**Pull request merged**
